### ISSUE TITLE
Error Installer Not Found when Installing Neovim Plugins with Packer

### ISSUE THREAD

**Issue by xzrie** [xshin404/myTermux#13]
I have installed it following the documentation, but I got an error when installing neovim plugin with packer, The error message shows
`status [ERROR INSTALLER NOT FOUND]`

Previously I also saw an error when Getting Information Repository, it shows
`(standard_in) 2: syntax error`

after installation, when i check `~/.config/` there is no nvim folder inside it.

I run it on Infinix Hot 10s with android version 11, here's the screenshot
![err_getting_info_repo](https://user-images.githubusercontent.com/68382685/130186280-8032aba9-5514-4c8f-8d1b-4d10afa20f15.jpeg)
![err_installer_not_found](https://user-images.githubusercontent.com/68382685/130186285-6e463f99-4d01-41c2-88e0-9b3bec2c73e7.jpeg)

**Comment by xshin404** [comment]
This error `status [ERROR INSTALLER NOT FOUND]` occurs because the NvChad repository no longer has the installer script, therefore the message `ERROR INSTALLER NOT FOUND` appears

![out](https://user-images.githubusercontent.com/66439853/130230281-810c78c5-6727-4985-b3fc-17a69d01ca06.png)

For this error message `(standard_in) 2: syntax error` occurs because the username in the NvChad repository has been changed to `NvChad/NvChad` while the previous username was `siduck76/NvChad`, therefore the fetch API error. You can look in the file `myTermux/.variable.sh` in the `REPOSITORY_APIS` variable section

![2021-08-20_18-57](https://user-images.githubusercontent.com/66439853/130230412-5ff5d1da-d1c8-4d72-9bc1-b6c5c5e0700c.png)

⚠️  How to fix the error?

1. ️ Installer not found

For the installer not found, you can solve it in 2 ways, namely:

First you can do a manual installation by going to the [NvChad](https://github.com/NvChad/NvChad) repository

Second, you can clone the old commit (which still has the installer script) or I have uploaded the [NvChad.zip](https://drive.google.com/file/d/1pnWybsiaVHpOrgAdbSx82vM8Gxz2bmoQ/view?usp=sharing) folder where there is still the installer script and I saved it on google drive. After you downloaded the [NvChad.zip](https://drive.google.com/file/d/1pnWybsiaVHpOrgAdbSx82vM8Gxz2bmoQ/view?usp=sharing) file, extract and execute the installer script it with the command `./install.sh -i`

2. ️ (standard_in) 2: syntax error

For this error, maybe I will update the REPOSITORY_APIS variable and change the correct username in the NvChad repository so that the fetch API does not error.

![2021-08-20_18-55](https://user-images.githubusercontent.com/66439853/130230798-4d31a2b8-e6d1-4d21-91c3-5fcae3536a98.png)

**Comment by xzrie** [comment]
> 
> 
> This error `status [ERROR INSTALLER NOT FOUND]` occurs because the NvChad repository no longer has the installer script, therefore the message `ERROR INSTALLER NOT FOUND` appears
> 
> ![out](https://user-images.githubusercontent.com/66439853/130230281-810c78c5-6727-4985-b3fc-17a69d01ca06.png)
> 
> For this error message `(standard_in) 2: syntax error` occurs because the username in the NvChad repository has been changed to `NvChad/NvChad` while the previous username was `siduck76/NvChad`, therefore the fetch API error. You can look in the file `myTermux/.variable.sh` in the `REPOSITORY_APIS` variable section
> 
> ![2021-08-20_18-57](https://user-images.githubusercontent.com/66439853/130230412-5ff5d1da-d1c8-4d72-9bc1-b6c5c5e0700c.png)
> 
> ⚠️ How to fix the error?
> 
>     1. ️ Installer not found
> 
> 
> For the installer not found, you can solve it in 2 ways, namely:
> 
> First you can do a manual installation by going to the [NvChad](https://github.com/NvChad/NvChad) repository or you can go to web documentation [nvchad.netlify.app](https://nvchad.netlify.app)
> 
> Second, you can clone the old commit (which still has the installer script) or I have uploaded the [NvChad.zip](https://drive.google.com/file/d/1pnWybsiaVHpOrgAdbSx82vM8Gxz2bmoQ/view?usp=sharing) folder where there is still the installer script and I saved it on google drive. After you downloaded the [NvChad.zip](https://drive.google.com/file/d/1pnWybsiaVHpOrgAdbSx82vM8Gxz2bmoQ/view?usp=sharing) file, extract and execute the installer script it with the command `./install.sh -i`
> 
>     1. ️ (standard_in) 2: syntax error
> 
> 
> For this error, maybe I will update the REPOSITORY_APIS variable and change the correct username in the NvChad repository so that the fetch API does not error.
> 
> ![2021-08-20_18-55](https://user-images.githubusercontent.com/66439853/130230798-4d31a2b8-e6d1-4d21-91c3-5fcae3536a98.png)

Thanks a lot! All of these are very helpful and my problem solved
